### ISSUE TITLE
Scores are visible at the end of each line

### ISSUE THREAD

**Issue by Kebab11noel** [missionarydev/board#3]
I use 1.13.2 and I get scores at the end of all lines, but in the example image there is no scores, this is a bug, or it is impossible to hide the scores in this version?
**What I get:**
![image](https://user-images.githubusercontent.com/45130268/48665090-f9bb3100-eaa8-11e8-950f-de79cab8c7a3.png)
**What I expect:**
![image](https://user-images.githubusercontent.com/45130268/48665138-bad9ab00-eaa9-11e8-8842-5ffa22e670d3.png)

**Comment by missionarydev** [comment]
It’s actually a forge mod that I made that hides the score numbers. Sorry :/
